version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          name: Install backend dependencies
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          name: Run backend tests
          command: |
            pipenv run pytest